// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// This module is the single source of truth for PDFX styling tokens.
// Update the exported `theme` object to customize component styles.

export const theme = {
  name: "professional",

  // Primitive scales.
  primitives: {
    typography: {
      xs: 10,
      sm: 12,
      base: 15,
      lg: 18,
      xl: 22,
      '2xl': 28,
      '3xl': 36,
    },
    spacing: {
      0: 0,
      0.5: 2,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 20,
      6: 24,
      8: 32,
      10: 40,
      12: 48,
      16: 64,
    },
    fontWeights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeights: {
      tight: 1.2,
      normal: 1.4,
      relaxed: 1.6,
    },
    borderRadius: {
      none: 0,
      sm: 2,
      md: 4,
      lg: 8,
      full: 9999,
    },
    letterSpacing: {
      tight: -0.025,
      normal: 0,
      wide: 0.025,
      wider: 0.05,
    },
  },

  // Semantic colors. Values must be valid for react-pdf.
  colors: {
    foreground: "#18181b",
    background: "#ffffff",
    muted: "#f4f4f5",
    mutedForeground: "#71717a",
    primary: "#4f46e5",
    primaryForeground: "#ffffff",
    border: "#e4e4e7",
    accent: "#3b82f6",
    destructive: "#dc2626",
    success: "#16a34a",
    warning: "#d97706",
    info: "#0ea5e9",
  },

  // Typography defaults.
  typography: {
    body: {
      fontFamily: "Helvetica",
      fontSize: 11,
      lineHeight: 1.6,
    },
    heading: {
      fontFamily: "Helvetica", // Cambiado a Helvetica para un look Modern
      fontWeight: 700,
      lineHeight: 1.25,
      fontSize: {
        h1: 32,
        h2: 24,
        h3: 20,
        h4: 16,
        h5: 14,
        h6: 12,
      },
    },
  },

  // Layout spacing.
  spacing: {
    page: {
      marginTop: 56,
      marginRight: 48,
      marginBottom: 56,
      marginLeft: 48,
    },
    sectionGap: 28,
    paragraphGap: 10,
    componentGap: 14,
  },

  // Page defaults.
  page: {
    size: "A4",
    orientation: "portrait",
  },
};
